--- #YAML:1.1
language: python
python:
    - "2.6"
    - "2.7"
env:
    - DB=postgres
before_script:
    - psql -c 'create database collectr;' -U postgres
notifications:
    irc:
        channels: "irc.freenode.org#linkuist"
        on_success: always
        on_failure: always

install: 
    - "pip install -r requirements/base.txt --use-mirrors"
    - "pip install -r requirements/tests.txt --use-mirrors"
script:
    - "cd collectr" 
    - "python manage.py syncdb --settings=settings_travis --noinput"
    - "python manage.py migrate --settings=settings_travis"
    - "python manage.py test source --settings=settings_travis collector source userprofile link_tracking semantism webfront"
services:
    - redis-server
